using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Common;
using System.Runtime.Serialization;
using Goliath.Data.Utils;

namespace Goliath.Data.Mapping
{
    [Serializable]
    [DataContract]
    public class Relation : Property
    {
        public Relation() { }
        public Relation(Property prop)
        {
            LazyLoad = prop.LazyLoad;
            IgnoreOnUpdate = prop.IgnoreOnUpdate;
            IsComplexType = prop.IsComplexType;
            ComplexTypeName = prop.ComplexTypeName;
            ConstraintType = prop.ConstraintType;
            DefaultValue = prop.DefaultValue;
            ConstraintName = prop.ConstraintName;
            PropertyName = prop.PropertyName;
            ColumnName = prop.ColumnName;
            ClrType = prop.ClrType;
            DbType = prop.DbType;
            Errors = prop.Errors;
            Length = prop.Length;
            Precision = prop.Precision;
            Scale = prop.Scale;
            IsNullable = prop.IsNullable;
            IsIdentity = prop.IsIdentity;
            IsAutoGenerated = prop.IsAutoGenerated;
            IsUnique = prop.IsUnique;
            IsPrimaryKey = prop.IsPrimaryKey;
            SqlType = prop.SqlType;

        }

        [DataMember]
        public RelationshipType RelationType { get; set; }
        [DataMember]
        public bool Exclude { get; set; }
        [DataMember]
        public string KeyFieldName { get; set; }
        [DataMember]
        public string ReferenceTable { get; set; }
        [DataMember]
        public string ReferenceColumn { get; set; }
        [DataMember]
        public string ReferenceTableSchemaName { get; set; }
        [DataMember]
        public string ReferenceConstraintName { get; set; }
        [DataMember]
        public string ReferenceEntityName { get; set; }
    }
}
